<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>capitulo-03-regressao-linear – tiagolafonso.github.io</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-ddd961a2510921635943dfbbd19534c4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">tiagolafonso.github.io</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#sec-regressao-linear" id="toc-sec-regressao-linear" class="nav-link active" data-scroll-target="#sec-regressao-linear">Regressão linear</a>
  <ul class="collapse">
  <li><a href="#sec-regressao-linear-simples" id="toc-sec-regressao-linear-simples" class="nav-link" data-scroll-target="#sec-regressao-linear-simples">Regressão Linear Simples</a>
  <ul class="collapse">
  <li><a href="#método-de-estimação" id="toc-método-de-estimação" class="nav-link" data-scroll-target="#método-de-estimação">Método de estimação</a></li>
  <li><a href="#estimar-regressão-simples-em-r" id="toc-estimar-regressão-simples-em-r" class="nav-link" data-scroll-target="#estimar-regressão-simples-em-r">Estimar regressão simples em R</a></li>
  <li><a href="#obter-os-resíduos-e-os-valores-previstos" id="toc-obter-os-resíduos-e-os-valores-previstos" class="nav-link" data-scroll-target="#obter-os-resíduos-e-os-valores-previstos">Obter os resíduos e os valores previstos</a></li>
  <li><a href="#interpretar-coeficientes" id="toc-interpretar-coeficientes" class="nav-link" data-scroll-target="#interpretar-coeficientes">Interpretar coeficientes</a></li>
  <li><a href="#visualizar-o-modelo-com-ggplot2" id="toc-visualizar-o-modelo-com-ggplot2" class="nav-link" data-scroll-target="#visualizar-o-modelo-com-ggplot2">Visualizar o modelo com <code>ggplot2</code></a></li>
  <li><a href="#visualizar-os-coeficientes" id="toc-visualizar-os-coeficientes" class="nav-link" data-scroll-target="#visualizar-os-coeficientes">Visualizar os coeficientes</a></li>
  </ul></li>
  <li><a href="#sec-regressao-linear-multipla" id="toc-sec-regressao-linear-multipla" class="nav-link" data-scroll-target="#sec-regressao-linear-multipla">Regressão Linear Múltipla</a>
  <ul class="collapse">
  <li><a href="#método-de-estimação-da-regressão-múltipla---método-dos-mínimos-quadrados-ols" id="toc-método-de-estimação-da-regressão-múltipla---método-dos-mínimos-quadrados-ols" class="nav-link" data-scroll-target="#método-de-estimação-da-regressão-múltipla---método-dos-mínimos-quadrados-ols">Método de estimação da regressão múltipla - Método dos mínimos quadrados (<em>OLS</em>)</a></li>
  <li><a href="#estimar-regressão-múltipla-no-r" id="toc-estimar-regressão-múltipla-no-r" class="nav-link" data-scroll-target="#estimar-regressão-múltipla-no-r">Estimar regressão múltipla no R</a></li>
  </ul></li>
  <li><a href="#sec-qualidade-ajuste" id="toc-sec-qualidade-ajuste" class="nav-link" data-scroll-target="#sec-qualidade-ajuste">Qualidade do ajuste do modelo de regressão</a>
  <ul class="collapse">
  <li><a href="#r-quadrado" id="toc-r-quadrado" class="nav-link" data-scroll-target="#r-quadrado">R Quadrado</a></li>
  <li><a href="#r-quadrado-ajustado" id="toc-r-quadrado-ajustado" class="nav-link" data-scroll-target="#r-quadrado-ajustado">R Quadrado ajustado</a></li>
  </ul></li>
  <li><a href="#sec-inferencia-estatistica" id="toc-sec-inferencia-estatistica" class="nav-link" data-scroll-target="#sec-inferencia-estatistica">Inferência estatística</a>
  <ul class="collapse">
  <li><a href="#teste-de-significância-individual-dos-coeficientes---teste-t" id="toc-teste-de-significância-individual-dos-coeficientes---teste-t" class="nav-link" data-scroll-target="#teste-de-significância-individual-dos-coeficientes---teste-t">Teste de significância individual dos coeficientes - teste t</a></li>
  <li><a href="#teste-de-significância-global-do-modelo---teste-f" id="toc-teste-de-significância-global-do-modelo---teste-f" class="nav-link" data-scroll-target="#teste-de-significância-global-do-modelo---teste-f">Teste de significância global do modelo - Teste F</a></li>
  <li><a href="#teste-de-significância-conjunta-dos-coeficientes" id="toc-teste-de-significância-conjunta-dos-coeficientes" class="nav-link" data-scroll-target="#teste-de-significância-conjunta-dos-coeficientes">Teste de significância conjunta dos coeficientes</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="sec-regressao-linear" class="level1">
<h1>Regressão linear</h1>
<p>Uma regressão é uma técnica que estabelece uma relação entre uma variável dependente e uma ou mais variáveis independentes. A regressão linear é um tipo de regressão que estabelece uma relação linear entre a variável dependente e as variáveis independentes. O objetivo é estudar o impacto das variáveis independentes na dependente. A variável dependente também pode ser definida como variável explicada, enquanto que as independentes também podem ser definidas como variáveis explicativas. Numa regressão a variável dependente é representada por <span class="math inline">\(y\)</span> e as variáveis independentes são representadas, genericamente, por <span class="math inline">\(x_1, x_2, ..., x_k\)</span>. O modelo de regressão linear é representado pela seguinte função:</p>
<p><span id="eq-modelo-geral"><span class="math display">\[
y = f(x_1, x_2,..., x_k)
\tag{1}\]</span></span></p>
<ul>
<li>Exemplo de uma aplicação de uma função: estudar o efeito do salário na produtividade dos trabalhadores. Neste caso, a variável dependente é a produtividade dos trabalhadores e a variável independente é o salário dos trabalhadores. O modelo de regressão linear é representado pela seguinte função:</li>
</ul>
<p><span id="eq-exemplo-produtividade"><span class="math display">\[
produtividade = f(salário)
\tag{2}\]</span></span></p>
<p>Neste caso vai ser analisado o efeito do salário na produtividade dos trabalhadores.</p>
<p>Também é usual utilizar os indices <span class="math inline">\(i\)</span>, <span class="math inline">\(t\)</span> e <span class="math inline">\(i,t\)</span> para representar uma função de acordo com os tipos de dados.</p>
<p>Função com dados seccionais:</p>
<p><span id="eq-dados-seccionais"><span class="math display">\[
y_i = f(x_{1i}, x_{2i}, ..., x_{ki})
\tag{3}\]</span></span></p>
<p>em que o <span class="math inline">\(i\)</span> representa a observação ou a entidade.</p>
<p>Função com séries temporais:</p>
<p><span id="eq-series-temporais"><span class="math display">\[
y_t = f(x_{1t}, x_{2t}, ..., x_{kt})
\tag{4}\]</span></span></p>
<p>em que o {t} representa o tempo.</p>
<p>Função com dados em painel:</p>
<p><span id="eq-dados-painel"><span class="math display">\[
y_{it} = f(x_{1it}, x_{2it}, ..., x_{kit})
\tag{5}\]</span></span></p>
<p>em que o <span class="math inline">\({i}\)</span> representa a entidade e o <span class="math inline">\({t}\)</span> representa o tempo.</p>
<section id="sec-regressao-linear-simples" class="level2">
<h2 class="anchored" data-anchor-id="sec-regressao-linear-simples">Regressão Linear Simples</h2>
<p>O modelo de regressão linear simples é um modelo que estabelece uma relação linear entre uma variável dependente e uma variável independente. Numa regressão simples as variável dependente é uma variável contínua e a variável independente pode ser uma variável contínua ou uma variável categórica. Mais à frente será abordado o caso de uma variável dependente categórica. O modelo de regressão linear simples é representado pelas regressões populacional e amostral. A regressão populacional é a relação entre a variável dependente e a variável independente na população. A regressão amostral é a relação entre a variável dependente e a variável independente na amostra. O modelo de regressão linear simples é representado pelas seguintes equações.</p>
<p>Regressão populacional:</p>
<p><span id="eq-regressao-populacional"><span class="math display">\[
y = \beta_0 + \beta_1 x
\tag{6}\]</span></span></p>
<p>Regressão amostral:</p>
<p><span id="eq-regressao-amostral"><span class="math display">\[
\hat{y} = \hat{\beta}_0 + \hat{\beta}_1 x + \epsilon
\tag{7}\]</span></span></p>
<p>em que:</p>
<ul>
<li><span class="math inline">\(y\)</span> é a variável dependente</li>
<li><span class="math inline">\(x\)</span> é a variável independente</li>
<li><span class="math inline">\(\beta_0\)</span> é a constante</li>
<li><span class="math inline">\(\beta_1\)</span> é o coeficiente angular</li>
<li><span class="math inline">\(\epsilon\)</span> é o erro aleatório</li>
</ul>
<p>O ^ significa estimativa. O erro aleatório é uma variável aleatória que representa a diferença entre o valor observado da variável dependente e o valor previsto da variável dependente através da regressão. O erro aleatório é representado pela seguinte equação:</p>
<p><span id="eq-erro-aleatorio"><span class="math display">\[
\epsilon = y - \hat{y}
\tag{8}\]</span></span></p>
<p>O <span class="math inline">\(\hat{y}\)</span> é o valor previsto da variável dependente e é calculado através dos coeficientes estimados <span class="math inline">\(\hat{\beta}_0\)</span> e <span class="math inline">\(\hat{\beta}_1\)</span> e dos valores de <span class="math inline">\(x\)</span> para cada observação.</p>
<section id="método-de-estimação" class="level3">
<h3 class="anchored" data-anchor-id="método-de-estimação">Método de estimação</h3>
<p>O objetivo da regressão linear é estimar os coeficientes <span class="math inline">\(\beta_0\)</span> e <span class="math inline">\(\beta_1\)</span> que minimizam a soma dos quadrados dos erros. Para este exemplos vamos utilizar o ficheiro <code>simple_reg.csv</code> que contém as variáveis <code>y</code> e <code>x</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#limpar ambiente</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>())</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co">#importar dados</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>dados <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"simple_reg.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>O método de estimação dos coeficientes <span class="math inline">\(\beta_0\)</span> e <span class="math inline">\(\beta_1\)</span> é o método dos mínimos quadrados ordinários (MQO). O método dos mínimos quadrados ordinários (MQO) é um método que minimiza a soma dos quadrados dos erros. O método do mínimo quadrado minimiza a distância entre as observações e a linha de regressão. Os coeficientes <span class="math inline">\(\beta_0\)</span> e <span class="math inline">\(\beta_1\)</span> são estimados da seguinte forma:</p>
<p><span id="eq-beta1-formula"><span class="math display">\[
\hat{\beta}_1 = \frac{\sum_{i=1}^{n} (x_i - \bar{x})(y_i - \bar{y})}{\sum_{i=1}^{n} (x_i - \bar{x})^2}= \frac{\sum_{i=1}^{n} x_i y_i - n \bar{x} \bar{y}}{\sum_{i=1}^{n} x_i^2 - n \bar{x}^2}
\tag{9}\]</span></span></p>
<p>em que:</p>
<ul>
<li><span class="math inline">\(x_i\)</span> é o valor da variável independente para a observação <span class="math inline">\(i\)</span></li>
<li><span class="math inline">\(\bar{x}\)</span> é a média dos valores da variável independente</li>
<li><span class="math inline">\(y_i\)</span> é o valor da variável dependente para a observação <span class="math inline">\(i\)</span></li>
<li><span class="math inline">\(\bar{y}\)</span> é a média dos valores da variável dependente</li>
<li><span class="math inline">\(n\)</span> é o número de observações</li>
</ul>
<p>No <code>R</code>podemos calcular o <span class="math inline">\(beta_1\)</span> da seguinte forma:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Número de observações</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(dados)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Médias</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>x_bar <span class="ot">&lt;-</span> <span class="fu">mean</span>(dados<span class="sc">$</span>x)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>y_bar <span class="ot">&lt;-</span> <span class="fu">mean</span>(dados<span class="sc">$</span>y)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co">#calculae beta1</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>beta1 <span class="ot">&lt;-</span> (<span class="fu">sum</span>(dados<span class="sc">$</span>x <span class="sc">*</span> dados<span class="sc">$</span>y) <span class="sc">-</span> n <span class="sc">*</span> x_bar <span class="sc">*</span> y_bar) <span class="sc">/</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>                (<span class="fu">sum</span>(dados<span class="sc">$</span>x<span class="sc">^</span><span class="dv">2</span>) <span class="sc">-</span> n <span class="sc">*</span> x_bar<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Resultados</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>beta1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6108889</code></pre>
</div>
</div>
<p>Onde a função <code>sum()</code> é utilizada para calcular a soma da coluna.</p>
<p>O coeficiente <span class="math inline">\(\beta_0\)</span> é calculado da seguinte forma:</p>
<p><span id="eq-beta0-formula"><span class="math display">\[
\hat{\beta}_0 = \bar{y} - \hat{\beta}_1 \bar{x}= \frac{\sum_{i=1}^{n} y_i}{n} - \hat{\beta}_1 \frac{\sum_{i=1}^{n} x_i}{n}
\tag{10}\]</span></span></p>
<p>Que podemos obter da seguinte forma já com o <span class="math inline">\(beta_1\)</span> obtido:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calcular beta0</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>beta0 <span class="ot">&lt;-</span> y_bar <span class="sc">-</span> beta1 <span class="sc">*</span> x_bar</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>beta0</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 15.11641</code></pre>
</div>
</div>
<p>Em que é minimizada a soma dos quadrados dos erros (<span class="math inline">\(SSE\)</span>) que é representada pela seguinte equação:</p>
<p><span id="eq-sse"><span class="math display">\[
SSE = \sum_{i=1}^{n} (y_i - \hat{y}_i)^2
\tag{11}\]</span></span></p>
<p>em que:</p>
<ul>
<li><span class="math inline">\(y_i\)</span> é o valor observado da variável dependente</li>
<li><span class="math inline">\(\hat{y}_i\)</span> é o valor previsto da variável dependente</li>
<li><span class="math inline">\(n\)</span> é o número de observações</li>
</ul>
<p>O coeficiente <span class="math inline">\(\beta_1\)</span> mede a mudança na variável dependente <span class="math inline">\(y\)</span> associada a uma unidade de mudança na variável independente <span class="math inline">\(x\)</span>. O coeficiente <span class="math inline">\(\beta_0\)</span> é a constante da linha de regressão e mede o valor da variável dependente <span class="math inline">\(y\)</span> quando a variável independente <span class="math inline">\(x\)</span> é igual a zero.</p>
</section>
<section id="estimar-regressão-simples-em-r" class="level3">
<h3 class="anchored" data-anchor-id="estimar-regressão-simples-em-r">Estimar regressão simples em R</h3>
<p>Existem várias funções que permitem estimar modelos de regressão em R sem utiliar muitos cáclulos. Podemos utilizar a função <code>lm()</code> que significa “linear model”. A função <code>lm()</code> tem a seguinte sintaxe:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x, <span class="at">data =</span> dados)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>em que:</p>
<ul>
<li><p><code>modelo</code> é o objeto que armazena o modelo de regressão</p></li>
<li><p><code>y</code> é a variável dependente</p></li>
<li><p><code>x</code> é a variável independente</p></li>
<li><p><code>data</code> é o conjunto de dados</p></li>
</ul>
<p>A variável dependente e a variável independente são separadas por <code>~</code>, que significa “em função de”.</p>
<p>A função <code>lm</code> tem várias opções que permitem personalizar o modelo de regressão. Aconstante é introduzida por defeito.</p>
<p>Podemos retirar a constante do modelo de regressão utilizando o argumento <code>-1</code> na fórmula. Por exemplo, podemos escrever o seguinte comando:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x <span class="sc">-</span> <span class="dv">1</span>, <span class="at">data =</span> dados)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Por exemplo, podemos retirar uma constante ao modelo de regressão, podemos adicionar termos de interação, podemos adicionar termos polinomiais, etc.</p>
<p>Os argumentos mais comuns da função <code>lm</code> são:</p>
<ul>
<li><p><code>formula</code>: fórmula que define o modelo de regressão</p></li>
<li><p><code>data</code>: conjunto de dados</p></li>
<li><p><code>subset</code>: subconjunto de observações</p></li>
<li><p><code>weights</code>: pesos das observações</p></li>
<li><p><code>na.action</code>: método para lidar com valores em falta</p></li>
</ul>
<p>Se utilizarmos os argumentos na ordem correta, podemos omitir os nomes dos argumentos. Por exemplo, podemos escrever o seguinte comando:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x, dados)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Mas se por alguma razão não quisermos utilizar a ordem dos argumentos, é necessário utilizar os nomes dos argumentos e um <code>=</code>. Por exemplo, podemos escrever o seguinte comando:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> dados, <span class="at">formula =</span> y <span class="sc">~</span> x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Esta opção pode ser útil quando pretendemos utilizar apenas alguns argumentos da função. Para ver todas as opções da função <code>lm</code>, podemos utilizar o comando <code>?lm</code> ou <code>help(lm)</code> diretamente na consola do R.</p>
<p>Exemplo de uma aplicação de uma regressão simples em R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#importar dados</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>dados <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"simple_reg.csv"</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co">#ver os dados</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dados)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  time      y   x
1    1  72.30 100
2    2  91.65 120
3    3 135.20 200
4    4  94.60 130
5    5 163.50 240
6    6 100.00 114</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">#estimar regressão simples</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x, <span class="at">data =</span> dados)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co">#ver resultados do modelo</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x, data = dados)

Residuals:
    Min      1Q  Median      3Q     Max 
-14.664  -3.913  -1.735   3.409  15.242 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 15.11641    6.56564   2.302   0.0335 *  
x            0.61089    0.03884  15.730 5.81e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.88 on 18 degrees of freedom
Multiple R-squared:  0.9322,    Adjusted R-squared:  0.9284 
F-statistic: 247.4 on 1 and 18 DF,  p-value: 5.808e-12</code></pre>
</div>
</div>
<p>A função <code>summary()</code> permite ver os resultados do modelo de regressão. O output apresenta os coeficientes estimados, o desvio padrão dos coeficientes, o valor t, o valor p, o R², o R² ajustado, o desvio padrão dos resíduos, o número de observações, etc.</p>
<p>Em vez de armazenar o modelo num objeto, também podemos insefrir a função <code>lm()</code> diretamente na função <code>summary()</code>, como no seguinte exemplo:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(y <span class="sc">~</span> x, <span class="at">data =</span> dados))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x, data = dados)

Residuals:
    Min      1Q  Median      3Q     Max 
-14.664  -3.913  -1.735   3.409  15.242 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 15.11641    6.56564   2.302   0.0335 *  
x            0.61089    0.03884  15.730 5.81e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.88 on 18 degrees of freedom
Multiple R-squared:  0.9322,    Adjusted R-squared:  0.9284 
F-statistic: 247.4 on 1 and 18 DF,  p-value: 5.808e-12</code></pre>
</div>
</div>
<p>Também é possível estimar a regressão simples com a biblioteca <code>tidymodels</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching packages ────────────────────────────────────── tidymodels 1.4.1 ──</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>✔ broom        1.0.10     ✔ recipes      1.3.1 
✔ dials        1.4.2      ✔ rsample      1.3.1 
✔ dplyr        1.1.4      ✔ tailor       0.1.0 
✔ ggplot2      4.0.0      ✔ tidyr        1.3.1 
✔ infer        1.0.9      ✔ tune         2.0.0 
✔ modeldata    1.5.1      ✔ workflows    1.3.0 
✔ parsnip      1.3.3      ✔ workflowsets 1.1.1 
✔ purrr        1.1.0      ✔ yardstick    1.3.2 </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ───────────────────────────────────────── tidymodels_conflicts() ──
✖ purrr::discard() masks scales::discard()
✖ dplyr::filter()  masks stats::filter()
✖ dplyr::lag()     masks stats::lag()
✖ recipes::step()  masks stats::step()</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Definir o modelo</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>modelo_spec <span class="ot">&lt;-</span> <span class="fu">linear_reg</span>() <span class="sc">|&gt;</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">set_engine</span>(<span class="st">"lm"</span>)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar o modelo</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>modelo_fit <span class="ot">&lt;-</span> modelo_spec <span class="sc">|&gt;</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">fit</span>(y <span class="sc">~</span> x, <span class="at">data =</span> dados)</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Ver resultados do modelo</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>modelo_fit</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>parsnip model object


Call:
stats::lm(formula = y ~ x, data = data)

Coefficients:
(Intercept)            x  
    15.1164       0.6109  </code></pre>
</div>
</div>
<p>Primeiro, definimos o modelo com a função <code>linear_reg()</code>, e esclhemos o motor de estimação com a função <code>set_engine()</code>. Posteriormente estimamos o modelo com a função <code>fit()</code>.</p>
<p>A biblioteca <code>tidymodels</code> é uma das mais completas para a análise de dados em <code>R</code>. É mais adequada para modelos complexos, por isso a sintáxe pode parece mais complicada. No entanto, não a podemos colocar de parte, uma vez que vai ser utilizada numa fase mais avaçada da econometria aplicada.</p>
</section>
<section id="obter-os-resíduos-e-os-valores-previstos" class="level3">
<h3 class="anchored" data-anchor-id="obter-os-resíduos-e-os-valores-previstos">Obter os resíduos e os valores previstos</h3>
<p>Os valores previstos são os valores da variável dependente estimados pelo modelo de regressão. Ou seja:</p>
<p><span id="eq-previsto"><span class="math display">\[
\hat{y} = \hat{\beta}_0 + \hat{\beta}_1 x
\tag{12}\]</span></span></p>
<p>Para os obter temos de substituir os valores de <span class="math inline">\(x\)</span> na equação considerando os valores dos coeficientes. De seguida vamos obter os valores previstos <span class="math inline">\(\hat{y}\)</span> (<code>y_hat</code>) com a função predict:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Obter os valores previstos</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>dados<span class="sc">$</span>y_hat <span class="ot">&lt;-</span> <span class="fu">predict</span>(modelo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Em alternativa à função <code>predict()</code> também seria possível recorrer à função <code>fitted()</code>. A função <code>predict()</code> e a função <code>fitted()</code> permitem obter os valores previstos da variável dependente a partir do modelo estimado. O valor previsto <span class="math inline">\(\hat{y}\)</span> é calculado através dos coeficientes estimados <span class="math inline">\(\hat{\beta}_0\)</span> e <span class="math inline">\(\hat{\beta}_1\)</span> e dos valores de <span class="math inline">\(x\)</span> para cada observação. Contudo a função <code>predict()</code> também permite prever a variável dependente considerando outros valores. Por exemplo, responder à questão “Qual seria o preço previsto de <span class="math inline">\(y\)</span> para um valor de <span class="math inline">\(x\)</span>=120?”. Então:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>y_previsto <span class="ot">&lt;-</span> <span class="fu">predict</span>(modelo, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">x =</span> <span class="dv">120</span>))</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>y_previsto</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
88.42308 </code></pre>
</div>
</div>
<p>A resposta seria 88.423. O argumento <code>newdata</code> permite especificar novos valores para as variáveis independentes.</p>
<p>Os resíduos são a diferença entre os valores observados e os valores previstos da variável dependente:</p>
<p><span id="eq-residuos"><span class="math display">\[
\hat{\epsilon} = y - \hat{y}
\tag{13}\]</span></span></p>
<p>Os valores dos resíduos <span class="math inline">\({\epsilon}\)</span> também poderiam ser obtidos através da diferença entre os valores observados e os valores previstos, que é basicamente a distância das observação em relação à reta do modelo linear. Para isso, podemos utilizar a função <code>residuals()</code> ou a função <code>resid()</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Obter os resíduos</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>dados<span class="sc">$</span>residuos <span class="ot">&lt;-</span> <span class="fu">residuals</span>(modelo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Para compararmos as colunas obtidas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Carregar bibliotecas</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="co">#ou</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ver os resultados</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>dados <span class="sc">|&gt;</span> <span class="fu">select</span>(y, y_hat, residuos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        y     y_hat     residuos
1   72.30  76.20530  -3.90529907
2   91.65  88.42308   3.22692287
3  135.20 137.29419  -2.09418941
4   94.60  94.53197   0.06803383
5  163.50 161.72975   1.77025446
6  100.00  84.75774  15.24225629
7   86.50  92.08841  -5.58841055
8  142.36 145.23575  -2.87574515
9  120.00 110.41508   9.58492234
10 112.56 117.13486  -4.57485559
11 132.30 130.57441   1.72558853
12 149.80 145.84663   3.95336595
13 115.30 129.96352 -14.66352257
14 132.20 135.46152  -3.26152270
15 149.50 140.95952   8.54047717
16 100.25 101.86263  -1.61263301
17  79.60  83.53597  -3.93596591
18  90.20  96.97552  -6.77552178
19 116.50 118.35663  -1.85663340
20 126.00 118.96752   7.03247770</code></pre>
</div>
</div>
</section>
<section id="interpretar-coeficientes" class="level3">
<h3 class="anchored" data-anchor-id="interpretar-coeficientes">Interpretar coeficientes</h3>
<p>Os coeficientes estimados do modelo de regressão linear simples podem ser interpretados da seguinte forma:</p>
<ul>
<li><p><span class="math inline">\(\hat{\beta_0}\)</span> (constante): representa o valor esperado de <span class="math inline">\(y\)</span> quando <span class="math inline">\(x = 0\)</span>. Por outras palavras, é o ponto onde a linha de regressão interceta o eixo <span class="math inline">\(y\)</span>.</p></li>
<li><p><span class="math inline">\(\hat{\beta_1}\)</span> (coeficiente de x): representa a variação esperada em <span class="math inline">\(y\)</span> para uma variação <strong>unitária</strong> em <span class="math inline">\(x\)</span>, mantendo todas as outras variáveis constantes (no caso de múltiplas variáveis independentes).</p></li>
</ul>
<p>É necessário ter muita atenção às unidades e às transformações feitas nas variáveis, pois isso pode afetar a forma como interpretamos o valor dos coeficientes.</p>
</section>
<section id="visualizar-o-modelo-com-ggplot2" class="level3">
<h3 class="anchored" data-anchor-id="visualizar-o-modelo-com-ggplot2">Visualizar o modelo com <code>ggplot2</code></h3>
<p>Para visualizar o modelo de regressão linear simples, podemos utilizar a biblioteca <code>ggplot2</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Para criar o gráfico de dispersão com a linha de regressão, podemos utilizar o seguinte código.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>dados <span class="sc">|&gt;</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y)) <span class="sc">+</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">linewidth =</span> <span class="fl">0.8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="capitulo-03-regressao-linear_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Podemos elaborar um pouco mais o gráfico ao adicionar a equação da reta, o valor de R², e criar legendas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimar modelo e criar etiqueta com equação e R²</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Criação de dados de exemplo para replicação, </span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="co"># uma vez que os seus não foram fornecidos</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="co"># O seu modelo de regressão</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x, <span class="at">data =</span> dados)</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>beta0 <span class="ot">&lt;-</span> <span class="fu">coef</span>(modelo)[<span class="dv">1</span>]</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>beta1 <span class="ot">&lt;-</span> <span class="fu">coef</span>(modelo)[<span class="dv">2</span>]</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>r2 <span class="ot">&lt;-</span> <span class="fu">summary</span>(modelo)<span class="sc">$</span>r.squared</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>label_eq <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">"y = "</span>, <span class="fu">round</span>(beta0, <span class="dv">3</span>), </span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>                 <span class="st">" + "</span>, <span class="fu">round</span>(beta1, <span class="dv">3</span>), </span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>                 <span class="st">" x</span><span class="sc">\n</span><span class="st">R² = "</span>, <span class="fu">round</span>(r2, <span class="dv">3</span>))</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Gráfico com melhor visualização</span></span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dados, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y)) <span class="sc">+</span></span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"steelblue"</span>, <span class="at">size =</span> <span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="fu">min</span>(dados<span class="sc">$</span>x) <span class="sc">+</span> <span class="dv">5</span>, <span class="at">y =</span> <span class="fu">max</span>(dados<span class="sc">$</span>y) <span class="sc">-</span> <span class="dv">5</span>,</span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a>                     <span class="at">label =</span> label_eq, <span class="at">hjust =</span> <span class="dv">0</span>, <span class="at">vjust =</span> <span class="dv">1</span>, </span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a>                     <span class="at">size =</span> <span class="dv">4</span>, <span class="at">fontface =</span> <span class="st">"bold"</span>) <span class="sc">+</span></span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Regressão Linear Simples"</span>,</span>
<span id="cb32-23"><a href="#cb32-23" aria-hidden="true" tabindex="-1"></a>             <span class="at">x =</span> <span class="st">"Variável Independente (x)"</span>,</span>
<span id="cb32-24"><a href="#cb32-24" aria-hidden="true" tabindex="-1"></a>             <span class="at">y =</span> <span class="st">"Variável Dependente (y)"</span>) <span class="sc">+</span></span>
<span id="cb32-25"><a href="#cb32-25" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="capitulo-03-regressao-linear_files/figure-html/plot_regression-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="visualizar-os-coeficientes" class="level3">
<h3 class="anchored" data-anchor-id="visualizar-os-coeficientes">Visualizar os coeficientes</h3>
<p>Com <code>sjPlot</code> é possível visualizar os coeficientes de forma gráfica.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Instalar e carregar a biblioteca sjPlot</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"sjPlot"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The following package(s) will be installed:
- sjPlot [2.9.0]
These packages will be installed into "~/livro-git/tiagolafonso.github.io/renv/library/windows/R-4.4/x86_64-w64-mingw32".

# Installing packages --------------------------------------------------------
- Installing sjPlot ...                         OK [linked from cache]
Successfully installed 1 package in 14 milliseconds.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'sjPlot'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:ggplot2':

    set_theme</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Criar o gráfico dos coeficientes</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(modelo,<span class="at">show.values =</span> <span class="cn">TRUE</span>, <span class="at">value.offset =</span> <span class="fl">0.3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="capitulo-03-regressao-linear_files/figure-html/plot_coef-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="sec-regressao-linear-multipla" class="level2">
<h2 class="anchored" data-anchor-id="sec-regressao-linear-multipla">Regressão Linear Múltipla</h2>
<p>O modelo de regressão linear múltipla é um modelo que estabelece uma relação linear entre uma variável dependente e duas ou mais variáveis independentes. O modelo de regressão linear múltipla para <span class="math inline">\(k\)</span> variáveis independentes é representado pela seguinte equação:</p>
<p>Regressão populacional:</p>
<p><span id="eq-regressao-multipla-pop"><span class="math display">\[
y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + ... + \beta_k x_k
\tag{14}\]</span></span></p>
<p>em que:</p>
<p>Os parâmetros <span class="math inline">\(\beta_0, \beta_1, \beta_2, ..., \beta_k\)</span> são os coeficientes que medem a relação entre a variável dependente <span class="math inline">\(y\)</span> e as variáveis independentes <span class="math inline">\(x_1, x_2, ..., x_k\)</span>. O coeficiente <span class="math inline">\(\beta_0\)</span> é a constante da linha de regressão e mede o valor da variável dependente <span class="math inline">\(y\)</span> quando todas as variáveis independentes <span class="math inline">\(x_1, x_2, ..., x_k\)</span> são iguais a zero.</p>
<p>Regressão amostral:</p>
<p><span id="eq-regressao-multipla-amost"><span class="math display">\[
\hat{y} = \hat{\beta}_0 + \hat{\beta}_1 x_1 + \hat{\beta}_2 x_2 + ... + \hat{\beta}_k x_k + \epsilon
\tag{15}\]</span></span></p>
<p>ou:</p>
<p><span id="eq-regressao-multipla-notacao"><span class="math display">\[
Y_i = \sum^{k}_{m=0}\beta_mX_{im}+\mu_i
\tag{16}\]</span></span></p>
<p>onde:</p>
<ul>
<li><p><span class="math inline">\(\hat{y}\)</span> é o valor estimado da variável dependente</p></li>
<li><p><span class="math inline">\(x_1, x_2, ..., x_k\)</span> são as variáveis independentes</p></li>
<li><p><span class="math inline">\(\beta_0\)</span> é a constante</p></li>
<li><p><span class="math inline">\(\hat{\beta}_0, \hat{\beta}_1, \hat{\beta}_2, ..., \hat{\beta}_k\)</span> são os coeficientes estimados</p></li>
<li><p><span class="math inline">\(\epsilon\)</span> é o erro</p></li>
</ul>
<p>A interpretação dos coeficientes <span class="math inline">\(\beta_1, \beta_2, ..., \beta_k\)</span> é a mesma que na regressão simples. O coeficiente <span class="math inline">\(\beta_1\)</span> mede a mudança na variável dependente <span class="math inline">\(y\)</span> associada a uma unidade de mudança na variável independente <span class="math inline">\(x_1\)</span> mantendo as outras variáveis independentes <span class="math inline">\(x_2, ..., x_k\)</span> constantes, ou seja, <em>ceteris paribus</em>.</p>
<p>Aplicação em R:</p>
<section id="método-de-estimação-da-regressão-múltipla---método-dos-mínimos-quadrados-ols" class="level3">
<h3 class="anchored" data-anchor-id="método-de-estimação-da-regressão-múltipla---método-dos-mínimos-quadrados-ols">Método de estimação da regressão múltipla - Método dos mínimos quadrados (<em>OLS</em>)</h3>
<p>O método de estimação dos coeficientes <span class="math inline">\(\beta_0, \beta_1, \beta_2, ..., \beta_k\)</span> é o método dos mínimos quadrados ordinários (MQO). O método dos mínimos quadrados ordinários (MQO) é um método que minimiza a soma dos quadrados dos erros. O método do mínimo quadrado minimiza a distância entre as observações e a linha de regressão. Os coeficientes <span class="math inline">\(\beta_0, \beta_1, \beta_2, ..., \beta_k\)</span> são estimados da seguinte forma com cálculo matricial:</p>
<p><span id="eq-regressao-matriz"><span class="math display">\[
\hat{\beta} = (X'X)^{-1}X'Y
\tag{17}\]</span></span></p>
<p>em que:</p>
<ul>
<li><p><span class="math inline">\(X\)</span> é a matriz de variáveis independentes</p></li>
<li><p><span class="math inline">\(Y\)</span> é o vetor da variável dependente</p></li>
<li><p><span class="math inline">\(\hat{\beta}\)</span> é o vetor de coeficientes estimados</p></li>
<li><p><span class="math inline">\(X'\)</span> é a transposta da matriz de variáveis independentes</p></li>
<li><p><span class="math inline">\((X'X)^{-1}\)</span> é a inversa da matriz de variáveis independentes</p></li>
</ul>
</section>
<section id="estimar-regressão-múltipla-no-r" class="level3">
<h3 class="anchored" data-anchor-id="estimar-regressão-múltipla-no-r">Estimar regressão múltipla no R</h3>
<p>Para este exemplo vamos utilizar os dados <code>hprice1</code> da biblioteca <code>wooldridge</code>. Para carregar os dados:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>())</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(wooldridge)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"hprice1"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Para ver a definição das variáveis recorrermos à documentação do conjunto de dados:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>?hprice1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>O conjunto de dados <code>hprice1</code> contém 88 observações e 10 variáveis. A variável dependente é o preço da casa (<code>price</code>) e algumas das variáveis independentes são: <code>lotsize</code> (tamanho do lote), <code>bdrms</code> (número de quartos), e <code>lotsize</code> (tamanho do lote). Neste exemplo de regressão múltipla vamos estimar o preço das casas com base nestas variáveis:</p>
<p><span id="eq-regressao-multipla-apl"><span class="math display">\[
price=\beta_0 + \beta_1 \cdot lotsize + \beta_2 \cdot bdrms + \epsilon
\tag{18}\]</span></span></p>
<p>Existem várias formas de estimar os coeficientes, entre elas, com cálculo matricial e com a função <code>lm()</code></p>
<section id="matrizes" class="level4">
<h4 class="anchored" data-anchor-id="matrizes">Matrizes</h4>
<p>Vamos estimar os coeficientes de acordo com a <a href="#eq-regressao-matriz" class="quarto-xref">Equation&nbsp;17</a>. Primeiro, vamos definir a variável dependente <code>Y</code> e a matriz de variáveis independentes <code>X</code>. A matriz <code>X</code> deve incluir uma coluna de 1’s para a constante.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>Y <span class="ot">&lt;-</span> hprice1<span class="sc">$</span>price</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(<span class="sc">~</span> lotsize <span class="sc">+</span> bdrms, <span class="at">data =</span> hprice1)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>X_t <span class="ot">&lt;-</span> <span class="fu">t</span>(X) <span class="co"># calcular a transposta de X'</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>X_t_X_inv <span class="ot">&lt;-</span> <span class="fu">solve</span>(X_t <span class="sc">%*%</span> X) <span class="co"># multiplicar X' por X</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>X_t_Y <span class="ot">&lt;-</span> X_t <span class="sc">%*%</span> Y</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>beta_hat <span class="ot">&lt;-</span> X_t_X_inv <span class="sc">%*%</span> X_t_Y</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>beta_hat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    [,1]
(Intercept) 63.262239424
lotsize      0.002858261
bdrms       57.312851121</code></pre>
</div>
</div>
<p>Para ver as matrizes e verificar que a coluna de 1’s foi criada com a função <code>model.matrix()</code>, a coluna de 1’s é normalmente designada por <span class="math inline">\(X_0\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(Y)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(X)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>De acordo com a <a href="#eq-regressao-matriz" class="quarto-xref">Equation&nbsp;17</a> vamos ter de:</p>
<ol type="1">
<li><p>Calcular a transporsta da matriz de variáveis independentes <span class="math inline">\(X\)</span> (<code>X_t</code>)</p></li>
<li><p>Multiplicar a matriz de <span class="math inline">\(X'\)</span> pela matriz <span class="math inline">\(X\)</span> e obter a inversa da matriz resultante <span class="math inline">\({X'X}^{-1}\)</span>, ou seja o objeto <code>X_t_X_inv</code>.</p></li>
<li><p>Multiplicar <span class="math inline">\(X'\)</span> pela matriz <span class="math inline">\(Y\)</span> para obter <span class="math inline">\(X'Y\)</span> (<code>X_t_Y</code>)</p></li>
<li><p>Multiplicar <span class="math inline">\({X'X}^{-1}\)</span> por <span class="math inline">\(X'Y\)</span> para obter os coeficientes estimados <span class="math inline">\(\hat{\beta}\)</span> (<code>beta_hat</code>)</p></li>
</ol>
</section>
<section id="função-lm" class="level4">
<h4 class="anchored" data-anchor-id="função-lm">Função <code>lm()</code></h4>
<p>Para estimar uma regressão múltipla no <code>R</code> de forma mais rápida, utilizamos a função <code>lm()</code>, como na regressão simples, com a seguinte sintaxe:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x2 <span class="sc">+</span> x3, <span class="at">data =</span> dados)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>em que as variáveis independentes <span class="math inline">\(x_1, x_2, ..., x_k\)</span> são separadas por <code>+</code>. Para estimar umo modelo de regressão múltipla com todas as variáveis independentes, utilizamos o seguinte comando:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> ., <span class="at">data =</span> dados)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Em que o <code>.</code> representa todas as variáveis independentes presentes no conjunto de dados (<code>data.frame</code>). Para estimar uma regressão múltipla sem a constante, utilizamos o seguinte comando:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x2 <span class="sc">+</span> ... <span class="sc">+</span> xk <span class="sc">-</span> <span class="dv">1</span>, <span class="at">data =</span> dados)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>em que, mais uma vez, o <code>- 1</code> indica que não pretendemos incluir a constante no modelo de regressão.</p>
<p>Estimar a regressão múltipla com a função <code>lm()</code> com <a href="#eq-regressao-multipla-apl" class="quarto-xref">Equation&nbsp;18</a>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(wooldridge)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(hprice1)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>modelo_2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(price <span class="sc">~</span> lotsize <span class="sc">+</span> bdrms, <span class="at">data =</span> hprice1)</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = price ~ lotsize + bdrms, data = hprice1)

Residuals:
     Min       1Q   Median       3Q      Max 
-239.420  -53.179   -5.284   34.195  286.567 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 6.326e+01  3.962e+01   1.597  0.11403    
lotsize     2.858e-03  9.001e-04   3.175  0.00209 ** 
bdrms       5.731e+01  1.088e+01   5.266 1.04e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 84.62 on 85 degrees of freedom
Multiple R-squared:  0.3368,    Adjusted R-squared:  0.3212 
F-statistic: 21.58 on 2 and 85 DF,  p-value: 2.627e-08</code></pre>
</div>
</div>
<p>Os coeficientes obtidos foram:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Variável</th>
<th>Coeficiente</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(Intercept)</td>
<td>63.262239424</td>
</tr>
<tr class="even">
<td>lotsize</td>
<td>0.002858261</td>
</tr>
<tr class="odd">
<td>bdrms</td>
<td>57.312851121</td>
</tr>
</tbody>
</table>
<p>A unidade do tamanho do lote (<code>lotsize</code>) é medida em <em>squared feet</em>, enquanto a unidade do número de quartos (<code>bdrms</code>) é medida em unidades e o preço (<code>price</code>) é medido em milhares de dólares. Então a interpretação dos coeficientes é a seguinte:</p>
<ul>
<li>O coeficiente da constante (intercept) indica que, quando o tamanho do lote e o número de quartos são iguais a zero, o preço esperado da casa é de 63.262239424 milhares de dólares.</li>
<li>O coeficiente de <code>lotsize</code> indica que, para cada aumento de uma unidade no tamanho do lote (em <em>squared feet</em>), o preço da casa aumenta em média 0.002858261 milhares de dólares (ou aproximadamente 2.858 dólares), <em>ceteris paribus</em> (mantendo todas as outras variáveis constantes)</li>
<li>O coeficiente de <code>bdrms</code> indica que, para cada aumento de uma unidade no número de quartos, o preço da casa aumenta em média 57.312851121 milhares de dólares (ou 57312.851121 dólares), <em>ceteris paribus</em>.</li>
</ul>
<p>Também podemos visualizar os coeficientes de uma regressão múltipla com a função <code>plot_model()</code> da biblioteca <code>sjPlot</code>, como foi feito na regressão simples:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Carregar a biblioteca sjPlot</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sjPlot)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a><span class="co">#criar o gráfico dos coeficientes</span></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_model</span>(modelo_2, <span class="at">show.values =</span> <span class="cn">TRUE</span>, <span class="at">value.offset =</span> <span class="fl">0.3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="capitulo-03-regressao-linear_files/figure-html/plot_coef_mult-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="qual-a-importância-de-ceteris-paribus" class="level4">
<h4 class="anchored" data-anchor-id="qual-a-importância-de-ceteris-paribus">Qual a importância de <em>ceteris paribus</em>?</h4>
<p>A expressão <em>ceteris paribus</em> é fundamental na econometria em economia, pois permite isolar o efeito de uma variável em relação a outra, mantendo todas as outras variáveis constantes. Isso é especialmente importante em modelos de regressão múltipla, onde várias variáveis independentes podem influenciar a variável dependente simultaneamente. Ao considerar o efeito de uma variável específica, como o número de quartos em uma casa, <em>ceteris paribus</em> garante que qualquer mudança observada no preço da casa seja atribuída exclusivamente a essa variável, sem a interferência de outras variáveis, como o tamanho do lote ou a localização, por exemplo. Isto permite uma análise mais precisa e confiável das relações causais entre as variáveis, facilita a tomada de decisão informada com base nos resultados do modelo econométrico.</p>
</section>
</section>
</section>
<section id="sec-qualidade-ajuste" class="level2">
<h2 class="anchored" data-anchor-id="sec-qualidade-ajuste">Qualidade do ajuste do modelo de regressão</h2>
<p>A qualidade do ajuste do modelo de regressão aos dados é medida através do coeficiente de determinação <span class="math inline">\(R^2\)</span> e do coeficiente de determinação ajustado <span class="math inline">\(R^2\)</span> ajustado. O <span class="math inline">\(R^2\)</span> varia de 0 a 1 e quanto mais próximo de 1, melhor o ajuste do modelo aos dados. Por exemplo um <span class="math inline">\(R^2\)</span> de 1 indica que 100% da variabilidade da variável dependente é explicada pelas variáveis independentes no modelo, ou seja, todos os pontos estão exatamente na linha de regressão. Um <span class="math inline">\(R^2\)</span> de 0 indica que nenhuma da variabilidade da variável dependente é explicada pelas variáveis independentes no modelo, ou seja, a linha de regressão é uma linha horizontal que passa pela média da variável dependente.</p>
<section id="r-quadrado" class="level3">
<h3 class="anchored" data-anchor-id="r-quadrado">R Quadrado</h3>
<p>O coeficiente de determinação <span class="math inline">\(R^2\)</span> é uma medida que indica a proporção da variabilidade da variável dependente que é explicada pelas variáveis independentes no modelo. Por outras palavras, o <span class="math inline">\(R^2\)</span> mede o quão bem o modelo de regressão se ajusta aos dados observados. O <span class="math inline">\(R^2\)</span> é calculado da seguinte forma:</p>
<p><span id="eq-r2-formula1"><span class="math display">\[
R^2 = 1 - \frac{SSE}{SST}
\tag{19}\]</span></span></p>
<p>em que:</p>
<ul>
<li><p><span class="math inline">\(SSE\)</span> é a soma dos quadrados dos erros: <span class="math inline">\(\sum_{i=1}^{n} (\epsilon_i)^2\)</span></p></li>
<li><p><span class="math inline">\(SST\)</span> é a soma total dos quadrados: <span class="math inline">\(\sum_{i=1}^{n} (y_i - \bar{y})^2\)</span></p></li>
</ul>
<p>onde:</p>
<ul>
<li><p><span class="math inline">\(\hat{y}_i\)</span> é o valor previsto da variável dependente para a observação <span class="math inline">\(i\)</span></p></li>
<li><p><span class="math inline">\(\bar{y}\)</span> é a média da variável dependente</p></li>
</ul>
<p>O erro contém toda a informação que o modelo não consegue explicar e essa informação é representada por <span class="math inline">\(SSE\)</span>. Enquanto que o <span class="math inline">\(SST\)</span> representa a informação que o modelo deveria explicar em condições ideais. Neste caso, o rácio entre <span class="math inline">\(SSE\)</span> e <span class="math inline">\(SST\)</span> indica a proporção da variabilidade que não é explicada pelo modelo que é retirada a 100% (1 - <span class="math inline">\(\frac{SSE}{SST}\)</span>).</p>
<p>O <span class="math inline">\(R^2\)</span> também pode ser calculado através de:</p>
<p><span id="eq-r2-formula2"><span class="math display">\[
R^2 = \frac{SSR}{SST}
\tag{20}\]</span></span></p>
<p>onde:</p>
<ul>
<li><span class="math inline">\(SSR\)</span> é a soma dos quadrados da regressão: <span class="math inline">\(\sum_{i=1}^{n} (\hat{y}_i - \bar{y})^2\)</span></li>
</ul>
<p>No R, o <span class="math inline">\(R^2\)</span> é apresentado por defeito na função <code>summary()</code> do objeto <code>lm</code>. Também pode ser calculado manualmente da seguinte forma:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co">#carregar dados</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>())</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(wooldridge)</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"hprice1"</span>)</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a><span class="co">#estimar modelo</span></span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(price <span class="sc">~</span> lotsize <span class="sc">+</span> bdrms, <span class="at">data =</span> hprice1)</span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular R^2 manualmente</span></span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a>SSE <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">residuals</span>(modelo)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a>SST <span class="ot">&lt;-</span> <span class="fu">sum</span>((hprice1<span class="sc">$</span>price <span class="sc">-</span> <span class="fu">mean</span>(hprice1<span class="sc">$</span>price))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a>R2 <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> SSE<span class="sc">/</span>SST</span>
<span id="cb51-13"><a href="#cb51-13" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"R^2:"</span>, <span class="fu">round</span>(R2, <span class="dv">4</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "R^2: 0.3368"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Ou</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>SSR <span class="ot">&lt;-</span> <span class="fu">sum</span>((<span class="fu">fitted</span>(modelo) <span class="sc">-</span> <span class="fu">mean</span>(hprice1<span class="sc">$</span>price))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>R2_ <span class="ot">&lt;-</span> SSR<span class="sc">/</span>SST</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"R^2_:"</span>, <span class="fu">round</span>(R2_, <span class="dv">4</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "R^2_: 0.3368"</code></pre>
</div>
</div>
<p>No output do objeto <code>modelo</code> obtido através da função <code>lm()</code>, podemos encontrar o valor do <span class="math inline">\(R^2\)</span> na penúltima linha com a designação <code>Multiple R-squared</code>summ. Portanto, com um <span class="math inline">\(R^2=0.3368\)</span> podemos concluir que as variáveis independentes explicam 33.68% da variação da variável dependente.</p>
<p>Existem algumas limitações do <span class="math inline">\(R^2\)</span>, nomeadamente:</p>
<ul>
<li>Um valor elevado do <span class="math inline">\(R^2\)</span> não significar necessariamente que o modelo é adequado.</li>
<li>O <span class="math inline">\(R^2\)</span> é uma medida de ajustamento do modelo que não tem consideração o número de variáveis independentes no modelo. Quanto mais variáveis independentes, maior o <span class="math inline">\(R^2\)</span>.</li>
<li>Elevada correlação entre variáveis independentes pode levar a um <span class="math inline">\(R^2\)</span> elevado.</li>
<li>Um <span class="math inline">\(R^2\)</span> muito baixo não indica necessariamente que as variáveis independentes não são adequadas.</li>
<li><span class="math inline">\(R^2\)</span> não é comparável entre modelos com diferentes transformações na variável dependente.</li>
</ul>
</section>
<section id="r-quadrado-ajustado" class="level3">
<h3 class="anchored" data-anchor-id="r-quadrado-ajustado">R Quadrado ajustado</h3>
<p>O <span class="math inline">\(R^2\)</span> ajustado é uma versão corrigida do R quadrado que é ajustado aos graus de liberdade do modelo. Os graus de liberdade são o número de observações menos o número de parâmetros estimados no modelo. Os graus de liberdade são basicamente o número de observações disponíveis para estimar os parâmetros do modelo. Portanto, o <span class="math inline">\(R^2\)</span> ajustado penaliza o modelo por cada variável independente adicional. O <span class="math inline">\(R^2\)</span> ajustado é sempre menor ou igual ao <span class="math inline">\(R^2\)</span>.</p>
<p>O <span class="math inline">\(R^2\)</span> ajustado é calculado da seguinte forma:</p>
<p><span id="eq-r2-ajustado"><span class="math display">\[
R^2_{ajustado} = 1 - \frac{SSE/(n-k-1)}{SST/(n-1)}
\tag{21}\]</span></span></p>
<p>em que:</p>
<ul>
<li><span class="math inline">\(n\)</span> é o número de observações</li>
<li><span class="math inline">\(k\)</span> é o número de variáveis independentes</li>
</ul>
<p>No <code>R</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular R^2 ajustado manualmente</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(hprice1)</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">coef</span>(modelo)) <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>SSE <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">residuals</span>(modelo)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>SST <span class="ot">&lt;-</span> <span class="fu">sum</span>((hprice1<span class="sc">$</span>price <span class="sc">-</span> <span class="fu">mean</span>(hprice1<span class="sc">$</span>price))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>R2_ajustado <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> (SSE<span class="sc">/</span>(n<span class="sc">-</span>k<span class="dv">-1</span>)) <span class="sc">/</span> (SST<span class="sc">/</span>(n<span class="dv">-1</span>))</span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"R^2 ajustado:"</span>, <span class="fu">round</span>(R2_ajustado, <span class="dv">4</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "R^2 ajustado: 0.3212"</code></pre>
</div>
</div>
<p>O <span class="math inline">\(R^2\)</span> ajustado tem a mesma interpretação que o <span class="math inline">\(R^2\)</span>. O <span class="math inline">\(R^2\)</span> ajustado pode ser utilizado para compara a qualidade de ajustamento de diferentes modelos de regressão com a mesma variável dependente.Por exemplo, se tivermos dois modelos de regressão, podemos comparar os <span class="math inline">\(R^2\)</span> ajustados dos dois modelos para determinar qual é o melhor modelo. No resultado de <code>summary(modelo)</code> o <span class="math inline">\(R^2\)</span> ajustado é apresentado na linha <code>Adjusted R-squared</code>.</p>
</section>
</section>
<section id="sec-inferencia-estatistica" class="level2">
<h2 class="anchored" data-anchor-id="sec-inferencia-estatistica">Inferência estatística</h2>
<p>A inferência estatística é utilizada para testar a significância estatística dos coeficientes estimados e a significância global do modelo. Quando os coeficientes são estatisticamente sigificantes e o modelo também, podemos generalizar os resultados para além da amostra.</p>
<section id="teste-de-significância-individual-dos-coeficientes---teste-t" class="level3">
<h3 class="anchored" data-anchor-id="teste-de-significância-individual-dos-coeficientes---teste-t">Teste de significância individual dos coeficientes - teste t</h3>
<p>Para testar a significância estatística dos coeficientes estimados, utilizamos o teste t. O teste t é utilizado para testar a hipótese nula de que o coeficiente é igual a zero. A hipótese alternativa é que o coeficiente é diferente de zero.</p>
<p>O valor t apresentado por defeito em qualquer software econométrico é de <span class="math inline">\(H_0: \beta_i = 0\)</span> e <span class="math inline">\(H_1: \beta_i \neq 0\)</span>. Ou seja, é um teste bidirecional. O valor t é calculado da seguinte forma:</p>
<p><span id="eq-teste-t"><span class="math display">\[
t_{stat} = \frac{\hat{\beta_i}-b}{SE(\hat{\beta_i})}
\tag{22}\]</span></span></p>
<p>em que:</p>
<ul>
<li><span class="math inline">\(\hat{\beta_i}\)</span> é o coeficiente estimado</li>
<li><span class="math inline">\(SE(\hat{\beta_i})\)</span> é o desvio padrão do coeficiente estimado</li>
<li>$ i$ é o número do coeficiente</li>
<li><span class="math inline">\(b\)</span> é o valor da hipótese nula (neste caso <span class="math inline">\(b=0\)</span>)</li>
</ul>
<p>Os coeficientes estimados são os valores de <span class="math inline">\(\hat{\beta}_0=15.11641\)</span> e <span class="math inline">\(\hat{\beta}_1=061098\)</span> que minimizam a soma dos quadrados dos erros. O desvio padrão (Std. Error) ou <span class="math inline">\(SE(\hat{\beta}_0)\)</span> mede a precisão das estimativas dos coeficientes. É calculado através da fórmula:</p>
<p><span id="eq-se-beta0"><span class="math display">\[
SE(\hat{\beta}_0) = \sqrt{ \hat{\sigma}^2 \left[ \frac{1}{n} + \frac{\bar{x}^2}{\sum_{i=1}^{n} (x_i - \bar{x})^2} \right] }
\tag{23}\]</span></span></p>
<p>em que:</p>
<ul>
<li><span class="math inline">\(\hat{\sigma}^2 = \frac{\sum_{i=1}^{n} (y_i - \hat{y}_i)^2}{n - 2}\)</span> é a variância residual estimada<br>
</li>
<li><span class="math inline">\((n)\)</span> é o número de observações</li>
<li><span class="math inline">\((\bar{x})\)</span> é a média de <span class="math inline">\((x_i)\)</span><br>
</li>
<li><span class="math inline">\(\sum_{i=1}^{n} (x_i - \bar{x})^2)\)</span> é a soma dos quadrados das diferenças de <span class="math inline">\((x)\)</span> em relação à média</li>
</ul>
<p>No R para ober o número de observações da amostra:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>())</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>dados <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"simple_reg.csv"</span>)</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Número de observações</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(dados<span class="sc">$</span>x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>O primeiro passo estimar o modelo e obter os resíduos e os valores previstos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimar o modelo</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x,dados)</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Obter valores previstos</span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>dados<span class="sc">$</span>y_hat <span class="ot">&lt;-</span> <span class="fu">predict</span>(modelo)</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a><span class="co">#obter resíduos</span></span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>dados<span class="sc">$</span>residuos <span class="ot">&lt;-</span> <span class="fu">residuals</span>(modelo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Assim, já é possível o valor de <span class="math inline">\(\hat{\sigma}^2\)</span>, <span class="math inline">\(\bar{x}\)</span> e <span class="math inline">\(S_{xx}\)</span>, <span class="math inline">\(Sxx\)</span> e <span class="math inline">\(SE_{\hat{\beta}_0}\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Variância residual estimada (sigma^2)</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>sigma2 <span class="ot">&lt;-</span> <span class="fu">sum</span>(dados<span class="sc">$</span>residuos<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> (n <span class="sc">-</span> <span class="dv">2</span>)</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Média de x</span></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>x_bar <span class="ot">&lt;-</span> <span class="fu">mean</span>(dados<span class="sc">$</span>x)</span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Soma dos quadrados de (x - x_bar)</span></span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a>Sxx <span class="ot">&lt;-</span> <span class="fu">sum</span>((dados<span class="sc">$</span>x <span class="sc">-</span> x_bar)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb59-9"><a href="#cb59-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-10"><a href="#cb59-10" aria-hidden="true" tabindex="-1"></a><span class="co"># desvio padrão de Beta0</span></span>
<span id="cb59-11"><a href="#cb59-11" aria-hidden="true" tabindex="-1"></a>SE_b0 <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(sigma2 <span class="sc">*</span> (<span class="dv">1</span><span class="sc">/</span>n <span class="sc">+</span> (x_bar<span class="sc">^</span><span class="dv">2</span> <span class="sc">/</span> Sxx)))</span>
<span id="cb59-12"><a href="#cb59-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-13"><a href="#cb59-13" aria-hidden="true" tabindex="-1"></a>SE_b0</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6.565638</code></pre>
</div>
</div>
<p>O desvio padrão do coeficiente <span class="math inline">\(\hat{\beta}_1\)</span> é calculado da seguinte forma:</p>
<p><span id="eq-se-beta1"><span class="math display">\[
SE(\hat{\beta}_1) = \sqrt{\frac{\hat{\sigma}^2}{\sum_{i=1}^{n} (x_i - \bar{x})^2}}
\tag{24}\]</span></span></p>
<p>em que:</p>
<ul>
<li><span class="math inline">\(\hat{\sigma}^2\)</span> é a variância residual estimada</li>
<li><span class="math inline">\(\sum_{i=1}^{n} (x_i - \bar{x})^2\)</span> é a soma dos quadrados das diferenças de <span class="math inline">\(x\)</span> em relação à média ou <span class="math inline">\(S_{xx}\)</span>. No R:</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co"># desvio padrão de Beta1</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>SE_b1 <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(sigma2 <span class="sc">/</span> Sxx)</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>SE_b1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.03883712</code></pre>
</div>
</div>
<p>Com os valores de <span class="math inline">\(SE(\hat{\beta}_0)\)</span> e <span class="math inline">\(SE(\hat{\beta}_1)\)</span>, podemos calcular a estatística t da <a href="#eq-teste-t" class="quarto-xref">Equation&nbsp;22</a>. No R, primeiro é necessário obter os coeficientes estimados do objeto <code>modelo</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Coeficientes estimados</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>beta0 <span class="ot">&lt;-</span> <span class="fu">coef</span>(modelo)[<span class="dv">1</span>]</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>beta1 <span class="ot">&lt;-</span> <span class="fu">coef</span>(modelo)[<span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>No código anterior obtivemos os valores de <span class="math inline">\(\hat{\beta_0}\)</span> e <span class="math inline">\(\hat{\beta_1}\)</span> por ordem de apresentação no modelo. Também é possível obter os valores através do nome do coeficiente:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Coeficientes estimados</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>beta0 <span class="ot">&lt;-</span> <span class="fu">coef</span>(modelo)[<span class="st">"(Intercept)"</span>]</span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>beta1 <span class="ot">&lt;-</span> <span class="fu">coef</span>(modelo)[<span class="st">"x"</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Como os valores de <span class="math inline">\(SE(\hat{\beta_0})\)</span> e <span class="math inline">\(SE(\hat{\beta_1})\)</span> já foram calculados, podemos calcular os valores t:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Valor t de Beta0</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>t_b0 <span class="ot">&lt;-</span> beta0 <span class="sc">/</span> SE_b0</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>t_b0</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
   2.302352 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Valor t de Beta1</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>t_b1 <span class="ot">&lt;-</span> beta1 <span class="sc">/</span> SE_b1</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>t_b1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       x 
15.72951 </code></pre>
</div>
</div>
<p>A distribuição do valor t é uma distribuição t de Student com <span class="math inline">\(n - 2\)</span> graus de liberdade, onde <span class="math inline">\(n\)</span> é o número de observações. Com isto podemos calcular o valor de probabilidade associado ao valor t. O valor p é a probabilidade de observar um valor t tão extremo quanto o observado, sob a hipótese nula de que o coeficiente é igual a zero. O valor p é calculado da seguinte forma:</p>
<p><span id="eq-valor-p"><span class="math display">\[
p = 2 \cdot P(T &gt; |t|)
\tag{25}\]</span></span></p>
<p>em que:</p>
<ul>
<li><span class="math inline">\(T\)</span> é uma variável aleatória que segue uma distribuição t de Student com <span class="math inline">\(n - 2\)</span> graus de liberdade</li>
<li><span class="math inline">\(t\)</span> é o valor t calculado anteriormente</li>
<li>2 é um fator de ajuste para o teste bidirecional (para um teste unidirecional (ex <span class="math inline">\(H1: \beta_i &gt; 0\)</span>), o fator seria 1)</li>
</ul>
<p>No R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Valor p de Beta0</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>p_b0 <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pt</span>(<span class="fu">abs</span>(t_b0), <span class="at">df =</span> n <span class="sc">-</span> <span class="dv">2</span>))</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>p_b0</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
 0.03346844 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Valor p de Beta1</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>p_b1 <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fu">pt</span>(<span class="fu">abs</span>(t_b1), <span class="at">df =</span> n <span class="sc">-</span> <span class="dv">2</span>))</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>p_b1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           x 
5.808243e-12 </code></pre>
</div>
</div>
<p>A <code>pt()</code> é a função de distribuição acumulada da distribuição t de Student. O <code>abs()</code> é a função valor absoluto (módulo). O <code>df</code> é o número de graus de liberdade. O <code>1 - pt()</code> é a probabilidade de observar um valor t maior que o valor t calculado. O <code>2 * (1 - pt())</code> é a probabilidade de observar um valor t tão extremo quanto o observado, sob a hipótese nula de que o coeficiente é igual a zero. Foi obtido um valor p de 0.033 para o <span class="math inline">\(beta_0\)</span> e de aproximadamente 0 para o <span class="math inline">\(beta_2\)</span>. Normalmente, estes valores de probabilidade são comparados com os valores de referência de 1%, 5% ou 10%. Rejeitamos a hipótese nula para um desses níveis quando o valor de p é inferior. Portanto, neste caso, a constante é estatisticamente diferente de zero para qualquer nível de significância, enquanto que para o <span class="math inline">\(beta_1\)</span> rejeitamos apenas para 5% e 10%. Também seria possível avaliar a significância estatística através do t-crítico(em que rejeitamos <span class="math inline">\(H0\)</span> se <span class="math inline">\(|t_{stat}| &gt; t_{crítico}\)</span>), contudo seria necessário calcualr um t-crítico para cada nível de significância estatística. O mesmo se aplicao ao intervalor de confiança que será explorado na próxima secção.</p>
<section id="intervalo-de-confiança" class="level4">
<h4 class="anchored" data-anchor-id="intervalo-de-confiança">Intervalo de confiança</h4>
<p>O intervalo de confiança dos coeficientes é obtido através da seguinte fórmula:</p>
<p><span id="eq-ic"><span class="math display">\[
IC(\hat{\beta}_i) = \hat{\beta}_i \pm t_{\alpha/2} \cdot SE(\hat{\beta}_i)
\tag{26}\]</span></span></p>
<p>em que:</p>
<ul>
<li><span class="math inline">\(IC(\hat{\beta}_i)\)</span> é o intervalo de confiança para o coeficiente <span class="math inline">\(\hat{\beta}_i\)</span></li>
<li><span class="math inline">\(t_{\alpha/2}\)</span> é o valor crítico da distribuição t de Student com <span class="math inline">\(n - 2\)</span> graus de liberdade e nível de significância <span class="math inline">\(\alpha\)</span></li>
<li><span class="math inline">\(SE(\hat{\beta}_i)\)</span> é o desvio padrão do coeficiente <span class="math inline">\(\hat{\beta}_i\)</span></li>
</ul>
<p>No <code>R</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Intervalo de confiança de Beta0</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>IC_b0 <span class="ot">&lt;-</span> <span class="fu">c</span>(beta0 <span class="sc">-</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> n <span class="sc">-</span> <span class="dv">2</span>) <span class="sc">*</span> SE_b0,</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>            beta0 <span class="sc">+</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> n <span class="sc">-</span> <span class="dv">2</span>) <span class="sc">*</span> SE_b0)</span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>IC_b0</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) (Intercept) 
   1.322515   28.910303 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Intervalo de confiança de Beta1</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>IC_b1 <span class="ot">&lt;-</span> <span class="fu">c</span>(beta1 <span class="sc">-</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> n <span class="sc">-</span> <span class="dv">2</span>) <span class="sc">*</span> SE_b1,</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>            beta1 <span class="sc">+</span> <span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df =</span> n <span class="sc">-</span> <span class="dv">2</span>) <span class="sc">*</span> SE_b1)</span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>IC_b1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        x         x 
0.5292952 0.6924827 </code></pre>
</div>
</div>
<p>A função <code>qt</code> é utilizada para calcular o valor crítico da distribuição t de Student para o nível de significância desejado. Neste caso, foi utilizado um nível de significância de 5% (0.05), o que corresponde a um intervalo de confiança de 95% (0.975 para o superior e 0.025 para o inferior). O <code>df</code> é o número de graus de liberdade. Para calcular o intervalo de confiança para outros níveis de significância estatística, basta alterar os valores do argumento <code>alpha</code> na função <code>qt()</code>. Podemos obter o intervalo de confiança utilizando a função <code>confint()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Intervalo de confiança dos coeficientes</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(modelo) <span class="co">#5%</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                2.5 %     97.5 %
(Intercept) 1.3225149 28.9103025
x           0.5292952  0.6924827</code></pre>
</div>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(modelo, <span class="at">level =</span> <span class="fl">0.90</span>) <span class="co">#10%</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  5 %       95 %
(Intercept) 3.7311746 26.5016428
x           0.5435429  0.6782349</code></pre>
</div>
</div>
<p>Com a biblioteca <code>stargazer</code>, podemos obter os intervalos de confiança de forma mais simples e rápida.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>())</span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>dados <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"simple_reg.csv"</span>)</span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x,dados)</span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Please cite as: </code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code> Hlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code> R package version 5.2.3. https://CRAN.R-project.org/package=stargazer </code></pre>
</div>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Resumo do modelo</span></span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a>modelo <span class="sc">%&gt;%</span></span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(modelo, <span class="at">type =</span> <span class="st">"text"</span>, <span class="at">ci =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
=============================================================
                                    Dependent variable:      
                              -------------------------------
                                             y               
                                    (1)             (2)      
-------------------------------------------------------------
x                                0.611***        0.611***    
                              (0.535, 0.687)  (0.535, 0.687) 
                                                             
Constant                         15.116**        15.116**    
                              (2.248, 27.985) (2.248, 27.985)
                                                             
-------------------------------------------------------------
Observations                        20              20       
R2                                 0.932           0.932     
Adjusted R2                        0.928           0.928     
Residual Std. Error (df = 18)      6.880           6.880     
F Statistic (df = 1; 18)        247.418***      247.418***   
=============================================================
Note:                             *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
<p>Através do intervalo de confiança podemos concluir que os coeficientes do modelo são estatisticamente diferentes de zero para um nível de significância de 5% e 10%, se o intervalo de confiança não inclui o valor zero (pois <span class="math inline">\(H0: \beta_i = 0\)</span>). Também é possível testar outras hipóteses como <span class="math inline">\(H_0: \beta_i = b\)</span>, em que <span class="math inline">\(b\)</span> é um valor qualquer. Se o intervalo de confiança não incluir o valor <span class="math inline">\(b\)</span>, rejeitamos a hipótese nula.</p>
</section>
</section>
<section id="teste-de-significância-global-do-modelo---teste-f" class="level3">
<h3 class="anchored" data-anchor-id="teste-de-significância-global-do-modelo---teste-f">Teste de significância global do modelo - Teste F</h3>
<p>O teste de significância global do modelo é utilizado para testar a hipótese nula de que todos os coeficientes são iguais a zero. Ou seja:</p>
<p><span id="eq-h0-f"><span class="math display">\[
H_0: \beta_1 = \beta_2 = ... = \beta_k = 0
\tag{27}\]</span></span></p>
<p>A hipótese alternativa é que pelo menos um dos coeficientes é diferente de zero. O teste de significância global do modelo é realizado através do teste F. O valor F é calculado da seguinte forma:</p>
<p><span id="eq-f-stat"><span class="math display">\[
F_{stat} = \frac{(SSR_{restrito} - SSR_{n restrito}) / q}{SSR_{n restrito} / (n - k - 1)}
\tag{28}\]</span></span></p>
<p>em que:</p>
<ul>
<li><span class="math inline">\(SSR_{restrito}\)</span> é a soma dos quadrados da regressão do modelo restrito (com os coeficientes nulos)</li>
<li><span class="math inline">\(SSR_{n restrito}\)</span> é a soma dos quadrados da regressão do modelo não restrito (com os coeficientes estimados)</li>
<li><span class="math inline">\(q\)</span> é o número de restrições (número de coeficientes nulos)</li>
<li><span class="math inline">\(n\)</span> é o número de observações</li>
<li><span class="math inline">\(k\)</span> é o número de variáveis explicativas</li>
</ul>
<p>No R vamos estimar o modelo restrito (<span class="math inline">\(y_i=\beta_0\)</span>) e o modelo não restrito (<span class="math inline">\(y_i=\beta_0 + \beta_1 x_i\)</span>):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="co">#carregar dados e estimar modelo</span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list =</span> <span class="fu">ls</span>())</span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a>dados <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"simple_reg.csv"</span>)</span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x,dados)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modelo restrito (só com constante)</span></span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>modelo_restrito <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> dados)</span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Modelo não restrito</span></span>
<span id="cb88-5"><a href="#cb88-5" aria-hidden="true" tabindex="-1"></a>modelo_n_restrito <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x, <span class="at">data =</span> dados)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Calcular o SSR para cada um dos modelos e o <span class="math inline">\(F_{stat}\)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular o SSR para cada um dos modelos:</span></span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a>SSR_restrito <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">residuals</span>(modelo_restrito)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a>SSR_n_restrito <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">residuals</span>(modelo_n_restrito)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb89-4"><a href="#cb89-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-5"><a href="#cb89-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular o F_stat</span></span>
<span id="cb89-6"><a href="#cb89-6" aria-hidden="true" tabindex="-1"></a>q <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">coef</span>(modelo_n_restrito)) <span class="sc">-</span> <span class="dv">1</span></span>
<span id="cb89-7"><a href="#cb89-7" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(dados)</span>
<span id="cb89-8"><a href="#cb89-8" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">coef</span>(modelo_n_restrito))</span>
<span id="cb89-9"><a href="#cb89-9" aria-hidden="true" tabindex="-1"></a>F_stat <span class="ot">&lt;-</span> ((SSR_restrito <span class="sc">-</span> SSR_n_restrito) <span class="sc">/</span> q) <span class="sc">/</span> (SSR_n_restrito <span class="sc">/</span> (n <span class="sc">-</span> k <span class="sc">-</span> <span class="dv">1</span>))</span>
<span id="cb89-10"><a href="#cb89-10" aria-hidden="true" tabindex="-1"></a>F_stat</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 233.6721</code></pre>
</div>
</div>
<p>Por fim podemos obter o valor p associado ao valor F com a função <code>pf()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular o valor p associado ao F_stat</span></span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>p_value <span class="ot">&lt;-</span> <span class="fu">pf</span>(F_stat, <span class="at">df1 =</span> q, <span class="at">df2 =</span> n <span class="sc">-</span> k <span class="sc">-</span> <span class="dv">1</span>, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a>p_value</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.2927e-11</code></pre>
</div>
</div>
<p>O valor p associado ao valor F também pode ser obtido firetamente do objeto <code>modelo</code> (está designado por <code>F-statistics ... p-value</code>) e através da função <code>anova()</code>. Concluímos que rejeitamos a hipótese nula de que todos os coeficientes são iguais a zero para qualquer nível de significância estatística.</p>
</section>
<section id="teste-de-significância-conjunta-dos-coeficientes" class="level3">
<h3 class="anchored" data-anchor-id="teste-de-significância-conjunta-dos-coeficientes">Teste de significância conjunta dos coeficientes</h3>
<p>O teste de significância conjunta dos coeficientes é utilizado para testar a hipótese nula de que um conjunto de coeficientes é igual a zero. Neste exemplo vamos utilizar mais uma vez o dados <code>hprice1</code> da biblioteca <code>wooldridge</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list=</span><span class="fu">ls</span>())</span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(wooldridge)</span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"hprice1"</span>)</span>
<span id="cb93-5"><a href="#cb93-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb93-6"><a href="#cb93-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimar o modelo</span></span>
<span id="cb93-7"><a href="#cb93-7" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(price <span class="sc">~</span> sqrft <span class="sc">+</span> bdrms <span class="sc">+</span> lotsize, <span class="at">data =</span> hprice1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Para testar a hipótese nula de que os coeficientes de <code>sqrft</code> e <code>bdrms</code> são iguais a zero (<span class="math inline">\(H0: \beta_{sqrft} = \beta_{bdrms} = 0\)</span>), podemos recorrer a função <code>linearHypothesis()</code> da biblioteca <code>car</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Teste de significância conjunta dos coeficientes</span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: carData</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'car'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:purrr':

    some</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    recode</code></pre>
</div>
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">linearHypothesis</span>(modelo, <span class="fu">c</span>(<span class="st">"sqrft = 0"</span>, <span class="st">"bdrms = 0"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Linear hypothesis test:
sqrft = 0
bdrms = 0

Model 1: restricted model
Model 2: price ~ sqrft + bdrms + lotsize

  Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
1     86 807257                                  
2     84 300724  2    506533 70.744 &lt; 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Neste caso a hipótese nula é rejeitada, indicando que os coeficientes de <code>sqrft</code> e <code>bdrms</code> são estatisticamente diferentes de zero. Para testar se <span class="math inline">\(H0: \beta_{lotsize} = \beta_{sqrft}\)</span>, podemos utilizar a mesma abordagem:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Teste de significância conjunta dos coeficientes</span></span>
<span id="cb101-2"><a href="#cb101-2" aria-hidden="true" tabindex="-1"></a><span class="fu">linearHypothesis</span>(modelo, <span class="st">"lotsize=sqrft"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Linear hypothesis test:
- sqrft  + lotsize = 0

Model 1: restricted model
Model 2: price ~ sqrft + bdrms + lotsize

  Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
1     85 593953                                  
2     84 300724  1    293230 81.907 4.701e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Por exemplo, para testar se estatisticamente o coeficiente de <code>lotsize</code> é o dobro do coeficiente de <code>sqrft</code>, podemos utilizar a seguinte abordagem:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Teste de significância conjunta dos coeficientes</span></span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a><span class="fu">linearHypothesis</span>(modelo, <span class="st">"lotsize=2*sqrft"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Linear hypothesis test:
- 2 sqrft  + lotsize = 0

Model 1: restricted model
Model 2: price ~ sqrft + bdrms + lotsize

  Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
1     85 601428                                  
2     84 300724  1    300704 83.994 2.764e-14 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>No próximo capítulo serão apresentados os pressupostos da regressão linear.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>